### ISSUE TITLE
Improvement - Login - Login Form Title and styling

### ISSUE THREAD

**Issue by NataliaAvila-PM** [zignaly-open/zigraffle#142]
### 1) Login Title
Please locate the title centered and a little bit up.
![image](https://user-images.githubusercontent.com/69221733/187173363-cd91f200-e740-44d6-9bae-6953c018a986.png)

As it was in the previous version:
https://ps2test-app.zignaly.com/login
![image](https://user-images.githubusercontent.com/69221733/187173325-fe775b3c-5e57-4c37-aaa0-c8aa0687be40.png)

----------------------------------------------------------------------------------

### 2) Login Fields Size 
Please reduce the size of the fields for the email address and password to be more similar to the old application:
![image](https://user-images.githubusercontent.com/69221733/187173652-70007543-beba-493d-af04-621e394da7a5.png)

As it was in the previous version:
https://ps2test-app.zignaly.com/login
![image](https://user-images.githubusercontent.com/69221733/187173714-aedce70e-004a-4cc1-a0c4-2692e21b8129.png)

**Comment by german-schneck** [comment]
Done

**Comment by NataliaAvila-PM** [comment]
Please @german-schneck link the task to the PR. Thanks

**Comment by Jennimar17** [comment]
✅resolved
