### ISSUE TITLE
BUG - Login - Login page title

### ISSUE THREAD

**Issue by NataliaAvila-PM** [zignaly-open/zigraffle#145]
In the log-in, the page name appears as "ZIGRaffle" instead of "Login - Zignaly"

![image](https://user-images.githubusercontent.com/69221733/187173985-a4f4b842-df73-4450-86bb-71321eff08e5.png)

**Comment by Xzirez** [comment]
@cwagner22 This is probably related to the Zigraffle text in PS2 you commented on the last PR.

**Comment by Xzirez** [comment]
https://github.com/zignaly-open/zigraffle/pull/147

**Comment by german-schneck** [comment]
Done

**Comment by NataliaAvila-PM** [comment]
Please @german-schneck link the task to the PR. Thanks

**Comment by Jennimar17** [comment]
✅resolved
