### ISSUE TITLE
2Fa Authentication Error

### ISSUE THREAD

**Issue by Jennimar17** [zignaly-open/zigraffle#149]
**1. new user - account not verified - not 2FA** 
coraliemaxon711@outlook.com Lavierose-1
It doesn't let me enter with the code sent to the email on the first try, if I update the web and log in again it doesn't ask me for a code and lets me enter normally.
![image](https://user-images.githubusercontent.com/62664863/187536899-739e49c4-d7c4-4d1e-a9c2-e1cbb271f52b.png)

**2.  user account confirmed - not 2Fa activated**
Christopher.Wesmr271993@gmail.com Lavierose-1
"Resend code" sends me the email "user disabled for multiple attempts"
only making 1 attempt. 
![image](https://user-images.githubusercontent.com/62664863/187537253-2c858937-51c4-4a52-84e8-f7ede2da05ce.png)
![image](https://user-images.githubusercontent.com/62664863/187538175-680faa47-5c2f-43da-aa2f-c60b53e5866e.png)
after dialing the code it lets me enter.

**3. user account confirmed - 2Fa activated**
svwkp3dpuuopdhz@sonjj.edu.pl Lavierose-1
when I have 2fa activated, it asks me for the two codes, when I send it the code generated by the "google authenticator" it receives it as correct. The code that you send me by mail does not.

![image](https://user-images.githubusercontent.com/62664863/187538507-a54290e8-8dcd-4a9d-b5d0-cf9f20cc72ba.png)
![image](https://user-images.githubusercontent.com/62664863/187538540-53dfbf6b-3263-4423-8d95-0a4e98b89147.png)

@NataliaAvila-PM updated!

**Comment by NataliaAvila-PM** [comment]
Hi @Jennimar17, you need to review this, please, because you are introducing the 2FA code as an email code. The 2FA is the 2-factor authentication, you need to enable it through the old web app.

**Comment by NataliaAvila-PM** [comment]
@Jennimar17 I am going to close this task because the items are included in this other: 
https://github.com/zignaly-open/zigraffle/issues/161
