### ISSUE TITLE
UX/UI Report Login

### ISSUE THREAD

**Issue by Jennimar17** [zignaly-open/zigraffle#150]
**BROWSERS: chrome, brave, edge, firefox (desktop). safari(ipad air 5ta), chrome (mobile >=360px android, )**

- [x] 2. It is important that the form is navigable with the keyboard and that when I hit enter, it sends the form, not that it sends me to "forgot password"
![20](https://user-images.githubusercontent.com/62664863/187271533-8d7dfa48-da99-40f5-bc34-f78f6014328b.gif)

- [x] 3. The Inputs should have a placeholder (which indicates what data and in what format should be entered)
![image](https://user-images.githubusercontent.com/62664863/188004116-4a79200d-458e-422c-a884-975e82a58467.png)

- [x] 4. Toasters: When I enter a wrong password, two error messages are displayed (below the mail and password iput) the toaster should display "WrongCredentials"
![image](https://user-images.githubusercontent.com/62664863/188004229-c797b235-4c3c-417f-916f-d9e71716a144.png)

- [x] 5. Likewise the error messages that appear after the user does not enter the code and closes the "Insert Code" modal should be Toasters
![image](https://user-images.githubusercontent.com/62664863/188004305-18a6834b-caf3-4e28-874d-8ba68cee251b.png)

- [x] 6. a toaster should be displayed when the code has been resent
![image](https://user-images.githubusercontent.com/62664863/188004424-7ff101b8-bc14-4ab0-b4cb-da3aec9136f0.png)

Modals:
- [x] 7. Modal Confirm New Device ( with 2Fa): The modal that appears when the user login on an old device (registered device) from a verified account, has 2Fa enabled: It should not have the title "Confirm New Device" since it is not a new device. It should go "Confirm Authenticator 2Fa Code"
![image](https://user-images.githubusercontent.com/62664863/188019536-95b2efa4-3841-471f-9652-2acf13679929.png)

***There is a design for this modal.

![image](https://user-images.githubusercontent.com/62664863/188180102-318e7e23-0a7b-4cc1-9e6d-dcf0cd269b73.jpeg)

**Comment by Jennimar17** [comment]
- "Login" should be centered
- The Inputs should have a placeholder (which indicates what data and in what format should be entered)
- “Forgot password?” should be below the input

![image](https://user-images.githubusercontent.com/62664863/187540921-a4d0bdab-c744-498e-975c-a58e711835d1.png)

- Toasters: When I enter a wrong password, two error messages are displayed (below the mail and password iput) the toaster should display "WrongCredentials"
![image](https://user-images.githubusercontent.com/62664863/187541775-86b24595-ffb4-426e-b457-8d029f812dcc.png)

- Likewise the error messages that appear after the user does not enter the code and closes the "Insert Code" modal should be Toasters
![image](https://user-images.githubusercontent.com/62664863/187543095-e19d33c3-e589-4c47-907b-6ec92b5b8cff.png)


- Modal  "Too Many Attempts" should be styled
![image](https://user-images.githubusercontent.com/62664863/187542301-bc6a8f44-cc8b-4f9a-837c-058918ca1101.png)

**Comment by NataliaAvila-PM** [comment]
@Jennimar17 I have added numbers besides each item reported to make easier to follow. 

Could you please in the issue 1 provide more information about browser? In any of my browsers I am able to replicate.

Additionally, for the moment, the responsiveness is not part of the scope, I removed the comments from the list and leave them here for the future. 

8. Responsive: the modal should adapt to different screens
- [ ] Modal Verify Your Email 
![image](https://user-images.githubusercontent.com/62664863/188012311-cf59b90a-7d6e-4628-874a-229742f24b3e.png)

- [ ] Modal Confirm New Device ( without 2Fa) 
![image](https://user-images.githubusercontent.com/62664863/188012351-e6fbece6-adca-4f38-a242-8c3baeddd50f.png)


- [ ] Modal Confirm New Device ( 2Fa + New device)
![image](https://user-images.githubusercontent.com/62664863/188012507-01121056-af65-48e6-afdc-7b623eba2861.png)

- [ ] Modal Confirm New Device ( with 2Fa) 
![image](https://user-images.githubusercontent.com/62664863/188012451-84071cec-d065-4dd4-a6b6-e00603b9f823.png)

- [ ] Modal Too Many Attempts
![image](https://user-images.githubusercontent.com/62664863/188027748-787b01a0-c347-4397-8900-2c3646fbef66.png)

- [ ] Modal Too Many Attempts + 2Fa
![image](https://user-images.githubusercontent.com/62664863/188030661-6b0434f8-a67f-4abc-bb4b-39b6cf09ea69.png)

**Comment by strrife** [comment]
@Jennimar17 what device have you got the issue with the vertical bar on?

**Comment by Jennimar17** [comment]
> @Jennimar17 what device have you got the issue with the vertical bar on?

@strrife I have deleted the problem from the list. I couldn't replicate the bug. (my browser settings maybe).

**Comment by Jennimar17** [comment]
@strrife @NataliaAvila-PM  updated list of tested browsers/devices

**Comment by strrife** [comment]
I understand that the auth verification modal looks somewhat different from the designs but let's please track it under a different issue and have the changes from https://github.com/zignaly-open/zigraffle/pull/183 merged as they have some useful fixes
