### ISSUE TITLE
BUG - Login - Verify new device wrong API calls

### ISSUE THREAD

**Issue by NataliaAvila-PM** [zignaly-open/zigraffle#161]
- [x] Confirm New Device ( without 2Fa):
When a user requires confirm new device only and correct code is introduced, it is returning error "wrong code"

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/69221733/187670834-6031e1b9-8010-48dd-b7a1-dde75a24bf9a.png">

The error is that we are making the call to the api endpoint: 
`new_api/user/verify_code/enable_user`
 
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/69221733/187671023-79dde3f1-f745-4a18-b5a3-066a9d6003de.png">

instead of: 
`new_api/known_device/verify`
 
<img width="862" alt="image" src="https://user-images.githubusercontent.com/69221733/187671606-3fb5b4e2-a16c-4be8-8faa-72981a8d7761.png">

and same occurs with the resend email API call. We are making the call to the api endpoint:
`new_api/user/resend_code/enable_user`
 
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/69221733/187695741-e9e809fa-5678-4867-b9ef-3a90a808b251.png">

instead of:
`new_api/known_device/resend`
 
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/69221733/187696003-4ca71e7d-6da7-4485-97ab-2f5886d3480f.png">

- [ ] when the user requires "Resend code" , user receives the mail that does not correspond "Your user is disabled"
![new device no 2fa-resend](https://user-images.githubusercontent.com/62664863/188053704-f5c43682-0e63-4583-b856-c7a51ce6146a.gif)
`christopher.wesmr271993@gmail.com pass: Lavierose-1`

Testing account:
user: `natalia+zig20211103@zignaly.com`
pass: `natalia+zig20211103@zignaly.com`

or 
user: `natalia+20211006@zignaly.com`
pass: `natalia+20211006@zignaly.com`

@NataliaAvila-PM

**Comment by Jennimar17** [comment]
- [ ] Verify Your Email:
`user: dustanniver.sar.y95.83@gmail.com / pass: Lavierose-1`
- [ ] When the user opens a new account and it has not been verified and tries to login, he never receives the email with the code the first time he requests it
![no mail verify account](https://user-images.githubusercontent.com/62664863/188048594-c0450cc5-70b1-4a09-b9f2-dff713aac4ee.gif)

- 2 calls are made to the same endpoint with two different request methods
`new_api/login`
OPTION and POST the OPTION response is 204
![image](https://user-images.githubusercontent.com/62664863/188050701-66dcad1c-7525-429f-a338-53c57ba9fb04.png)
![image](https://user-images.githubusercontent.com/62664863/188050769-1419bec5-5f65-40cc-ac73-9f1831fe4dd2.png)

- [ ] when the user requires "Resend code" , user receives the mail that does not correspond "Your user is disabled"
![no mail verify account-resend](https://user-images.githubusercontent.com/62664863/188051872-8e87ca0d-9c6c-411f-9c23-5b6d57900995.gif)
2 calls are made to the same endpoint with two different request methods
OPTION and POST the OPTION response is 204
`new_api/user/resend_code/enable_user`
- [ ] when the user sends the code received by mail: User can login with the code received by mail to verify his account after requests it “Resend Code” 

- [ ] Confirm New Device ( 2Fa + New device):when the user enters from a new device and has 2Fa activated, he only sends the authenticator code correctly and not the email code
![Confirm New Device ( 2Fa + New device)](https://user-images.githubusercontent.com/62664863/188058662-03f38735-354e-4d83-8249-0100c42075ce.gif)

- [ ] Too Many Attempts: 
`sweetcap.tai.n.4.9.2.9@gmail.com`
![image](https://user-images.githubusercontent.com/62664863/188060434-3b4056f0-0dd4-4746-afc8-e79bbaec8f9f.png)


- [ ] Modal Too Many Attempts + 2Fa: 
The user cannot send the code received by mail, after many attempts to enter the account
`user: svwkp3dpuuopdhz@sonjj.edu.pl/ pass: Lavierose-1`
![too many+2fa](https://user-images.githubusercontent.com/62664863/188059739-25a476dd-10fd-40c9-8725-a1f3f6c8b561.gif)

@NataliaAvila-PM
