### ISSUE TITLE
BUG - Header Component

### ISSUE THREAD

**Issue by Jennimar17** [zignaly-open/zigraffle#168]
- [ ]  The logo should be centered on the cross axis (it can be seen above than in the design) 

- [ ] Menu/Dropdown: is not displayed as per design when the menu is displayed
![image](https://user-images.githubusercontent.com/62664863/188249810-0cbf15ac-a60b-48ba-b680-ed4a18be1637.png)

**Comment by NataliaAvila-PM** [comment]
Jennifer, this is out of the scope right now:
- [ ] Header Login/Logout Component: Items marked in red are missing.
![image](https://user-images.githubusercontent.com/62664863/188247680-0ca2e09e-1dd7-4f5f-a45f-74b844d17ed8.png)

Also icon was changed, so no need for using the same as figma
- [ ] the user icon is not the same as in the design
![image](https://user-images.githubusercontent.com/62664863/188249096-4dda7e32-86f8-4de9-bd76-173c02c02111.png)

I have removed it from the comments.

**Comment by NataliaAvila-PM** [comment]
Removed this one also from the comments. I believe is not need it.
- [ ] the bottom bar is not shown on the active or selected page/link
![image](https://user-images.githubusercontent.com/62664863/188248740-831790ad-822e-47f7-95fc-12f23ef06a5f.png)

Also the ones about responsive are out of scope right now:
- [ ] Header is not responsive: responsive view looks broken on 360px devices (smaller screen on android). 
- [ ] Header elements should be rearranged for mobile view. ***a Hamburger menu could be applied in this case to improve the user experience***
![image](https://user-images.githubusercontent.com/62664863/188001818-e2d59642-daac-4509-940e-ad8a134a14f4.png)

**Comment by NataliaAvila-PM** [comment]
Migrated: https://3.basecamp.com/5165237/buckets/28665489/todos/5342634073
