### ISSUE TITLE
BUG - My Dashboard - Page and table improvements

### ISSUE THREAD

**Issue by Jennimar17** [zignaly-open/zigraffle#182]
**Page**
1. - [ ] the name of the page should be My Dashboard not Closed Positions
![image](https://user-images.githubusercontent.com/62664863/188752748-7e42c1b2-a741-4c9b-bb0c-2327cbc751f5.png)

2. - [ ]  the page is not translated
![image](https://user-images.githubusercontent.com/62664863/189167237-593f52af-1ff2-4519-b75a-6a8327d36b52.png)

@NataliaAvila-PM updated!

**Comment by NataliaAvila-PM** [comment]
Please @Jennimar17 check always twice that the page that you are reporting the bugs is test-app.zignaly.com and not https://ps2test-app.zignaly.com/
In this case the error is in both but be careful with this.

**Comment by Jennimar17** [comment]
**Table**
1. - [ ] the icons are not shown in the items of the header table
![image](https://user-images.githubusercontent.com/62664863/189170110-c7624c51-3b97-446d-8268-1e837eddbddf.png)

**Modal**
1. - [ ]  the % of Success Fee is missing
![image](https://user-images.githubusercontent.com/62664863/189171097-54d2d458-e2b7-4a88-a3f2-3c21e13e16b9.png)
![image](https://user-images.githubusercontent.com/62664863/189171900-2e0d9aa4-0565-43a3-9b47-888d954b77f1.png)
![image](https://user-images.githubusercontent.com/62664863/189172288-541fafc0-7f6b-4b5b-a56b-e9e9c866d220.png)

2. - [ ]  the logic of this bar is contrary. when the user moves it towards Reinvest it is because he wants to reinvest and NOT withdraw, so its value must be 100% and not 0% and vice versa in case the user moves the bar towards withdraw
![image](https://user-images.githubusercontent.com/62664863/189172563-75a82385-1116-49e6-a870-0ab1fa408df2.png)
![bar](https://user-images.githubusercontent.com/62664863/189174694-1951d2bc-abdb-4b77-8e92-6d22f3c379e1.gif)

**Comment by NataliaAvila-PM** [comment]
rearranged on https://github.com/zignaly-open/zigraffle/issues/208 and https://github.com/zignaly-open/zigraffle/issues/207
