### ISSUE TITLE
Improvement - Edit Investment - Modals Style

### ISSUE THREAD

**Issue by NataliaAvila-PM** [zignaly-open/zigraffle#188]
- [ ] Could we please reduce the font weight on these texts to 400 instead of 500? It looks too heavy. Thanks in advance!

<img width="674" alt="image" src="https://user-images.githubusercontent.com/69221733/189194495-eb827cba-e5e6-452f-96e7-4bf6a8ed5e1a.png">

- [x] Withdraw modal style:

Please if you can review the following items:
1. Missing line in between. 
2. Checking the composition, the margin on the left is greater than the one on the right
3. Align the texts to start on the same line

<img width="830" alt="image" src="https://user-images.githubusercontent.com/69221733/189308911-34536388-e7be-4c0d-9d5c-d0ce734a030d.png">

**Comment by Jennimar17** [comment]
"soft" and "hard disconnection" are links, they must lead to their respective destinations
![image](https://user-images.githubusercontent.com/62664863/189245271-4e175734-7fa2-44fb-acf4-5fd75a4d1756.png)

**Comment by strrife** [comment]
Re hard/soft disconnects, for now we do not have the help pages. Also, @NataliaAvila-PM, maybe we should have not a link but a tooltip?

**Comment by strrife** [comment]
Additionally, I think the correct grammar would be "as soon as the trader frees enough funds from any open position" instead of "as soon as the trader free enough funds from any open positions"

**Comment by strrife** [comment]
[] when clicking into the InputAmount, the text input should be focused. Right now you have to click precisely into the inout

**Comment by NataliaAvila-PM** [comment]
> Re hard/soft disconnects, for now, we do not have the help pages. Also, @NataliaAvila-PM, maybe we should not have a link but a tooltip?
Agree. We leave it for the next release.

> when clicking the currency amount in the amount input, the text input should be focused. Right now, this is not the case.
More than focused or additionally to focus is that the 0 is not a placeholder as in invest more, and it stays there.
![2022-09-16 17 06 26](https://user-images.githubusercontent.com/69221733/190671136-92de28b8-5874-49e7-af71-5b0f6e0fa132.gif)

Also, pending the font weight in the texts in the modals to reduce from 500 to 400.

**Comment by NataliaAvila-PM** [comment]
migrated to: https://3.basecamp.com/5165237/buckets/28665489/todos/5342661457
