### ISSUE TITLE
BUG -  Pending Transactions - transaction list

### ISSUE THREAD

**Issue by Jennimar17** [zignaly-open/zigraffle#192]
- [ ] each transaction must be shown separately.
The amounts should not be grouped by type, since the time can vary for each transaction.

![image](https://user-images.githubusercontent.com/62664863/189249338-086b9918-89e4-41a1-8559-a1b45adb04d0.png)

**Comment by NataliaAvila-PM** [comment]
It is ok that transactions are grouped by type, they are executed in next PSDS all together
