### ISSUE TITLE
BUG - My dashboard - Edit investment modal

### ISSUE THREAD

**Issue by NataliaAvila-PM** [zignaly-open/zigraffle#193]
**Modal**
1. - [x]  the % of Success Fee is missing
![image](https://user-images.githubusercontent.com/62664863/189171097-54d2d458-e2b7-4a88-a3f2-3c21e13e16b9.png)
![image](https://user-images.githubusercontent.com/62664863/189171900-2e0d9aa4-0565-43a3-9b47-888d954b77f1.png)

2. - [x]  the logic of this bar is contrary. when the user moves it towards Reinvest it is because he wants to reinvest and NOT withdraw, so its value must be 100% and not 0% and vice versa in case the user moves the bar towards withdraw
![image](https://user-images.githubusercontent.com/62664863/189172563-75a82385-1116-49e6-a870-0ab1fa408df2.png)
![bar](https://user-images.githubusercontent.com/62664863/189174694-1951d2bc-abdb-4b77-8e92-6d22f3c379e1.gif)

**Comment by strrife** [comment]
fixed in https://github.com/zignaly-open/zigraffle/pull/221

**Comment by NataliaAvila-PM** [comment]
both issues are fixed!! 🎉 thanks!
