### ISSUE TITLE
BUG - Czech Language missing in selector

### ISSUE THREAD

**Issue by NataliaAvila-PM** [zignaly-open/zigraffle#207]
I can not yet select our test language Czech in the language selector
![image](https://user-images.githubusercontent.com/69221733/189871011-786351ec-c421-4d7e-b87c-8c56c9892bde.png)

**Comment by strrife** [comment]
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/5725161/190527930-5ae379fc-240e-4ddc-9132-7ab0cb05a773.png">

**Comment by NataliaAvila-PM** [comment]
have you added the translations with all the characters on purpose?? XD
![image](https://user-images.githubusercontent.com/69221733/190660224-be6d90b3-4999-46bf-98f6-dcff7b3ab8f0.png)
