### ISSUE TITLE
BUG - Page Titles

### ISSUE THREAD

**Issue by NataliaAvila-PM** [zignaly-open/zigraffle#208]
- [ ] My Dashboard appears as Closed Positions
![image](https://user-images.githubusercontent.com/69221733/189873561-34505814-0887-4ea1-ab8e-9d7f73200536.png)

 
 
- [x] Service Pages. Right now, all of them appear as "Trading Services - Zignaly." When the URL is the service id, the page title should be "Service name - Zignaly". If it is one of the pages of the owner, it should include it in the name "Service name | Section - Zignaly". In this case, for example, it should be "Happy Koala | Management - Zignaly". Following a similar structure that the current web:
![image](https://user-images.githubusercontent.com/69221733/189872220-6a293084-b164-4afa-af04-fe31fc432ca9.png)
![image](https://user-images.githubusercontent.com/69221733/189872911-4da0390f-067f-47dc-9f66-f9c69d76c4d4.png)

**Comment by NataliaAvila-PM** [comment]
Migrated: https://3.basecamp.com/5165237/buckets/28665489/todos/5342680498

**Comment by Jennimar17** [comment]
the language has been resolved, the name of the page has not been resolved
![image](https://user-images.githubusercontent.com/62664863/191083571-42a53ffe-d969-49c4-8954-ae101c165487.png)

**Comment by NataliaAvila-PM** [comment]
Jennifer from now on we are managing this from Basecamp. Thanks
