### ISSUE TITLE
BUG - Investors - Table

### ISSUE THREAD

**Issue by NataliaAvila-PM** [zignaly-open/zigraffle#210]
- [x] 1. Strange scroll on the right side of the table
![image](https://user-images.githubusercontent.com/69221733/189913217-567cc537-7bfc-4c40-acd7-b6642a77750c.png)
![image](https://user-images.githubusercontent.com/69221733/189913374-407a1db1-3800-4bc2-a548-a3c6a04eac92.png)

- [ ] 2. The show and hide columns look like they have broken checkboxes, and the separation between items is greater than it should be. German fixed this in his branch, so maybe wait for merging. 
![image](https://user-images.githubusercontent.com/69221733/189912995-2f70f70e-4c5b-4d66-a482-d7d7dab5b2ae.png)

- [x] 3. Too much white space on the top area above the table. Please move the table up
![image](https://user-images.githubusercontent.com/69221733/189913632-e46fae7d-6b9c-4715-94c4-c44d16143622.png)

I have removed issue about freezing the first column

- [ ] 4. An issue with the column selector. it looks like we bring back a previous issue with the dropdown of the column selector:
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/69221733/190248226-33f2aa62-bd34-4cbd-8045-514aec267d1a.png"> 

- [ ] 5. Now on the right side of the table, it looks like we are not adapting the table size to the window size. The table should be the one having the scroll, not the window
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/69221733/190249493-2eb5be1d-0b1b-49b1-85dd-82327a1f0aa0.png">

**Comment by strrife** [comment]
I will also do an enhancement to fix hard-to-distinguish check/cross icons
![image](https://user-images.githubusercontent.com/5725161/189999064-7ee7b66b-4db9-4e52-a585-860a179a91aa.png)

**Comment by NataliaAvila-PM** [comment]
reopened until is reviewed

**Comment by NataliaAvila-PM** [comment]
Pending issues reviewed @strrife . Summary below:

Issues fixed:
1. Strange scroll on the right side of the table
2. Column Selector. Checkboxes Fixed3. 
3. Too much Space on the top

Issues Pending:
2. Column Selector -> Separation between items
4. Column selector is not properly located.
5. Table is now not fitting in the window. Window it shows a horizontal scroll

**Comment by NataliaAvila-PM** [comment]
Migrated: https://3.basecamp.com/5165237/buckets/28665489/todos/5342668357
