### ISSUE TITLE
BUG - Favicon

### ISSUE THREAD

**Issue by NataliaAvila-PM** [zignaly-open/zigraffle#211]
Please update the favicon with the new style 
![image](https://user-images.githubusercontent.com/69221733/189914779-2a7d2b7c-c4ef-4f86-b8ba-f18b799defc1.png)

**Comment by strrife** [comment]
Fixed in https://github.com/zignaly-open/zigraffle/pull/215

**Comment by strrife** [comment]
Re-opening since I am not the verifier

**Comment by NataliaAvila-PM** [comment]
Some issues with the cache in Safari, but working on Chrome. 
<img width="684" alt="image" src="https://user-images.githubusercontent.com/69221733/190247488-1665510d-6f75-435b-b59a-d5cdef391b8a.png">
