### ISSUE TITLE
BUG - Top Menu - User without services redirecting to help page

### ISSUE THREAD

**Issue by NataliaAvila-PM** [zignaly-open/zigraffle#214]
URL: https://test-app.zignaly.com/help
Username (email): natalia+01234@zignaly.com
Steps to reproduce: 
- Login with the user and access the section "For Trading Services".
- This user doesn't have any service, and it redirects him to zignaly.com/help
![image](https://user-images.githubusercontent.com/69221733/189874942-796ec12a-de7d-4c93-a9a3-a0a4216aec6b.png)

Expected result: If the user doesn't have any service (in the user API response, "isTrader.profit_Sharing" = False
![image](https://user-images.githubusercontent.com/69221733/189875566-eeb33ba4-3d07-4b2c-a092-aafb73f5656d.png)

Then we should redirect the user to /become_trader. The title of that page will be "Become a trader - Zignaly". In the future, it will have a landing page style, to inform about the advantages of being a trader in Zignaly.

**Comment by strrife** [comment]
I thought this was the expected behavior @NataliaAvila-PM 
So we just replace /help with /become-trader ?

**Comment by NataliaAvila-PM** [comment]
yes please

**Comment by NataliaAvila-PM** [comment]
Is it possible that it is that the button is the one that redirects the user to one place or the other and not the URL? so if a trader with services visits "https://test-app.zignaly.com/become_trader" he can access but if he clicks on

<img width="996" alt="image" src="https://user-images.githubusercontent.com/69221733/190659139-b3389620-22b4-4528-9e59-ed982f07ec21.png"> 

he is redirected to https://test-app.zignaly.com/profit-sharing/62c360f1e27c3e7e6c3e1394

**Comment by NataliaAvila-PM** [comment]
Migrated: https://3.basecamp.com/5165237/buckets/28665489/todos/5342650798
