### ISSUE TITLE
BUG - Edit Investment - Transfers not updated after a transfer out

### ISSUE THREAD

**Issue by NataliaAvila-PM** [zignaly-open/zigraffle#224]
When an investor transfers out pending funds from new investment, the funds are reduced immediately from the balance. For this reason, the pending transaction list should be reloaded to show the new funds pending:

![2022-09-14 12 10 48](https://user-images.githubusercontent.com/69221733/190128433-87a1db2a-22e2-4b17-b987-a68391ee53a7.gif)

**Comment by strrife** [comment]
I've fixed this but I've also noticed a strange behavior: withdrawing $1 and then $2 results in a pending withdrawal of $2, not $3 @NataliaAvila-PM

**Comment by NataliaAvila-PM** [comment]
Yes, the withdrawal replaces the previous withdrawal amount. We should maybe review this to make it more clear in the modal. Adding a task with that improvement: https://github.com/zignaly-open/zigraffle/issues/257

This one is fixed and working. Thanks!
