### ISSUE TITLE
BUG - 1password blue highlight

### ISSUE THREAD

**Issue by strrife** [zignaly-open/zigraffle#235]
![image](https://user-images.githubusercontent.com/5725161/190442720-3b4f9d65-566e-4370-9d5c-89ad8dd23f5a.png)

**Comment by NataliaAvila-PM** [comment]
Still reviewing due to a background with high contrast:
<img width="571" alt="image" src="https://user-images.githubusercontent.com/69221733/190658370-8ad04bed-ce16-42da-85b1-33ba27d70781.png">

**Comment by NataliaAvila-PM** [comment]
moved to Basecamp
https://3.basecamp.com/5165237/buckets/28665489/todos/5342625984
