### ISSUE TITLE
Improvement(PS2): fix i18n structure

### ISSUE THREAD

**Issue by strrife** [zignaly-open/zigraffle#243]
In multiple translation files there's a top-level object that is 146% redundant
![image](https://user-images.githubusercontent.com/5725161/190531513-432d1c4c-ad95-431d-a0b4-0e240725c492.png)
![image](https://user-images.githubusercontent.com/5725161/190531527-2f37f764-5144-4e08-bd66-6378a9605f05.png)
![image](https://user-images.githubusercontent.com/5725161/190531547-a20fd99f-a010-483f-9722-936b43d575a2.png)

**Comment by NataliaAvila-PM** [comment]
Migrated: https://3.basecamp.com/5165237/buckets/28665489/todos/5342732995
